services:
  app:
    build: ./app
    container_name: tailwind-css
    volumes:
      - node_modules:/app/node_modules
      - ./app/src:/app
    ports:
      - 7080:8080
#    command: ["tail", "-f", "/dev/null"]

volumes:
  node_modules:
